name: Call Docker Image CI

on:
  push:
    branches:
    - master
    - develop

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io

jobs:

  call-workflow-passing-data:
      uses: CJN-Team/pet-project-services/.github/workflows/docker_ci.yml@main

